### ISSUE TITLE
Error: `A_constructor_cannot_have_a_this_parameter` when running `vsce package`

### ISSUE THREAD

**Issue by sdankel** [FuelLabs/sway-vscode-plugin#91]
I tried running `vsce package -o sway-vscode-plugin-dev.vsix` per the README, and I get this error:

```
Executing prepublish script 'npm run vscode:prepublish'...

> sway-vscode-plugin@0.2.4 vscode:prepublish /Users/sophiedankel/Development/sway-vscode-plugin
> npm run compile


> sway-vscode-plugin@0.2.4 compile /Users/sophiedankel/Development/sway-vscode-plugin
> tsc -b

/Users/sophiedankel/Development/sway-vscode-plugin/node_modules/typescript/lib/tsc.js:5771
        A_constructor_cannot_have_a_this_parameter: diag(2681, ts.DiagnosticCategory.Error, "A_constructor_cannot_have_a_this_parameter_2681", "A constructor cannot
                                                                                                                                               ^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/Users/sophiedankel/Development/sway-vscode-plugin/node_modules/typescript/bin/tsc:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
```

Going back to commits from several months ago, I still get this error.

**Comment by sdankel** [comment]
This no longer repros.
